name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images
        run: docker-compose build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Start services
        run: docker-compose up -d
      - name: Check if Elasticsearch is up
        run: |
          until curl -fs http://localhost:9200; do
            echo "Waiting for Elasticsearch..."
            sleep 5
          done
      - name: Check if Kibana is up
        run: |
          until curl -fs http://localhost:5601; do
            echo "Waiting for Kibana..."
            sleep 5
          done
      - name: Check if Logstash is up
        run: |
          until curl -fs http://localhost:9600; do
            echo "Waiting for Logstash..."
            sleep 5
          done
      - name: Run integration tests
        run: echo "Run your integration tests here"
      - name: Clean up
        run: docker-compose down

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Production
        run: echo "Deploying to production server"
